<?php
/**
 * Created by PhpStorm.
 * User: f-oris
 * Date: 2019/6/18
 * Time: 10:45 AM
 */

namespace EasySmartProgram\Http;

use EasySmartProgram\Application;
use EasySmartProgram\Support\Exception\InvalidConfigException;
use EasySmartProgram\Support\Http\ResponseHandler;

/**
 * Class HttpClient
 * @package EasySmartProgram\Http
 * @author  f-oris <us@f-oris.me>
 * @version 1.0.0
 */
class HttpClient extends \EasySmartProgram\Support\Http\HttpClient
{
    /**
     * @var Application
     */
    protected $app;

    /**
     * @var bool
     */
    protected $withAccessToken = true;

    /**
     * @var string
     */
    protected $responseType = ResponseHandler::TYPE_COLLECTION;

    /**
     * HttpClient constructor.
     * @param Application $app
     */
    public function __construct(Application $app)
    {
        $this->app = $app;
        parent::__construct($app->config['http_client'] ?? []);
    }

    /**
     * @param array $config
     * @return \EasySmartProgram\Support\Http\HttpClient
     * @throws InvalidConfigException
     */
    public function setConfig(array $config = [])
    {
        if ($config['response_type'] == ResponseHandler::TYPE_GUZZLE_RESPONSE) {
            throw new InvalidConfigException(
                sprintf('Unsupport response type [%s]!', ResponseHandler::TYPE_GUZZLE_RESPONSE)
            );
        }
        return parent::setConfig($config); // TODO: Change the autogenerated stub
    }

    /**
     * @return $this
     */
    public function withAccessToken()
    {
        $this->withAccessToken = true;
        return $this;
    }

    /**
     * @return $this
     */
    public function withoutAccessToken()
    {
        $this->withAccessToken = false;
        return $this;
    }

    /**
     * @param string $url
     * @param string $method
     * @param array  $options
     * @return mixed
     * @throws \EasySmartProgram\Support\Exception\InvalidConfigException
     * @throws \EasySmartProgram\Support\Exception\RuntimeException
     * @throws \GuzzleHttp\Exception\GuzzleException
     * @throws \Psr\Cache\InvalidArgumentException
     */
    public function request(string $url, $method = 'GET', $options = [])
    {
        if ($this->withAccessToken && empty($options['query']['access_token'])) {
            $options['query']['access_token'] = $this->app->access_token->getAccessToken();
        }

        return $this->handleResponse(parent::request($url, $method, $options));
    }

    /**
     * @param $response
     * @return mixed
     */
    protected function handleResponse($response)
    {
        // reset next request with access token
        $this->withAccessToken();

        return $response;
    }
}